### ISSUE TITLE
Changes requested for AppCenter

### ISSUE THREAD

**Issue by cassidyjames** [bytepixie/snippetpixie#14]
Thanks for submitting an app to AppCenter! However, we have a few issues we came across that will need to be resolved. This looks like a cool app, so I hope you can get any issues resolved so it can be released to users! Let me know if you have any questions.

### Non-functional

Using the [test version built by AppCenter Dashboard](http://packages.elementary.io/testing/pool/main/c/com.github.bytepixie.snippetpixie/com.github.bytepixie.snippetpixie0.9.2-a8b1aa.deb), I am unable to get this to work. I've entered several strings but they are never replaced. Running the `--start` command from Terminal shows a segmentation fault after a short time, so perhaps that is related.

### AppData

Another small issue was this line in the AppData: 

https://github.com/bytepixie/snippetpixie/blob/4a9ffc735a09fa18fa61db5852ad465ec0685191/data/com.github.bytepixie.snippetpixie.appdata.xml.in#L14

1. It's not an issue to users of elementary OS (where this AppData will be displayed) that your app only runs on elementary OS,
2. We typically discourage mentioning the platform name (elementary OS) in the AppData anyway, as it's redundant and irrelevant to users,
3. If for some reason it makes sense, elementary must always be lower-cased according to the [brand guidelines](https://elementary.io/brand).

I think the best way forward there would just be to remove the line from the AppData.

**Comment by ianmjones** [comment]
Thanks @cassidyjames, good call on the branding etc., I'll see if I can debug that `.deb`.

**Comment by ianmjones** [comment]
Hey @cassidyjames, I'm struggling to reproduce the error, cleared out my Snippet Pixie installation and installed that `.deb` you linked, worked for me. :disappointed: 

Please could you tell me which application you were trying to expand snippets in?

Also, what was the snippet's abbreviation string?

If you get a chance, please could you do the following... 

1. In Terminal, run `export G_MESSAGES_DEBUG=all`
1. Then run `com.github.bytepixie.snippetpixie --start`
1. Switch to the app you want to expand in and enter the abbreviation
1. Switch back to Terminal and `ctrl-c` if it hasn't already died.

Please then send me the output you'll see in the terminal.

Thanks!

**Comment by cassidyjames** [comment]
@ianmjones I found that the segfault was after using [Ideogram](https://appcenter.elementary.io/com.github.cassidyjames.ideogram/). 

Other than that, I just don't get any text expansion. Maybe I'm doing something wrong? If I type 

>addr`

into the "Abbreviation" entry, and then 

>123 Sesame St.

into the body textview, when I type 

>addr`

into an app (like Quilter or NoteJot), it should automatically replace it with 

>123 Sesame St.

…right? Is there some other hotkey I'm missing or something?

Here's my output from running `G_MESSAGES_DEBUG=all com.github.bytepixie.snippetpixie --start` and attempting to expand something in Quilter:

```
(com.github.bytepixie.snippetpixie:3952): Gtk-DEBUG: 22:59:22.384: Connecting to session manager

(com.github.bytepixie.snippetpixie:3952): GLib-GObject-CRITICAL **: 22:59:22.424: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
** (com.github.bytepixie.snippetpixie:3952): DEBUG: 22:59:25.081: Application.vala:224: <<< WINDOW DEACTIVATE EVENT Type ='window:deactivate', Source: 'G_MESSAGES_DEBUG=all com.github.bytepixie.snippetpixie --start'
** (com.github.bytepixie.snippetpixie:3952): DEBUG: 22:59:25.082: Application.vala:214: >>> WINDOW ACTIVATE EVENT Type ='window:activate', Source: 'Quilter'
** (com.github.bytepixie.snippetpixie:3952): DEBUG: 22:59:25.140: Application.vala:270: $$$ Found focsed child control.
** (com.github.bytepixie.snippetpixie:3952): DEBUG: 22:59:35.068: Application.vala:224: <<< WINDOW DEACTIVATE EVENT Type ='window:deactivate', Source: 'Quilter'
** (com.github.bytepixie.snippetpixie:3952): DEBUG: 22:59:35.068: Application.vala:214: >>> WINDOW ACTIVATE EVENT Type ='window:activate', Source: 'G_MESSAGES_DEBUG=all com.github.bytepixie.snippetpixie --start'
```

**Comment by ianmjones** [comment]
Thanks for the extra info @cassidyjames, I can reproduce the segfault triggered by using Ideogram, guess I'll be diving into your code to see what it's doing that Snippet Pixie can't handle!

> …right? Is there some other hotkey I'm missing or something?

Yep, absolutely how it should be, no hot keys needed. Snippet Pixie currently only watches for normal key strokes and shift-key strokes, but that means "abbr`" should be fine.

Thanks for the debug info, I think I might have a fix for that.
