### ISSUE TITLE
Hitting tab key after editing new snippet name doesn't select snippet text placeholder

### ISSUE THREAD

**Issue by phase1geo** [bytepixie/snippetpixie#20]
When I create a new snippet, Snippet Pixie correctly selects the placeholder text in the abbreviation field which allows me to begin typing the new abbreviation immediately; however, when I hit the Tab key, the placeholder text in the snippet body widget is not automatically selected.

**Comment by ianmjones** [comment]
Thanks @phase1geo, that's a great idea, I'll see if I can get it working.
