### ISSUE TITLE
Snippet expansion is unreliable

### ISSUE THREAD

**Issue by jtrees** [bytepixie/snippetpixie#21]
**Describe the bug**
After starting the app snippet expansion works once and then stops working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the app or use `com.github.bytepixie.snippetpixie --start`
2. Keep it running
3. Type the snippet trigger into the global Application menu
4. Notice how expansion works
5. Close and re-open the Application menu
6. Type the snippet trigger into the global Application menu

**Expected behaviour**
Snippet expansion should work as it did before.

**Desktop (please complete the following information):**
 - OS: elementary OS 5.0 Juno
 - Snippet Pixie Version: 0.9.3

**Comment by ianmjones** [comment]
Thanks for the bug report @jtrees.

If you get a chance, please could you do the following...

1. In Terminal, run `com.github.bytepixie.snippetpixie --stop`
1. Then run `export G_MESSAGES_DEBUG=all`
1. Then run `com.github.bytepixie.snippetpixie --start`
1. Run your steps 3-6 to reproduce the problem
1. Switch back to Terminal and ctrl-c if it hasn't already died.

Please then send me the output you'll see in the terminal.

Thanks!

**Comment by jtrees** [comment]
Thanks for the quick response.

I'm actually unable to reproduce the issue now... Which is good. :)

I'll re-open the issue if I encounter this again and can provide some output according to your instructions.

Cool app by the way.
