### ISSUE TITLE
Doesn't expand text in Google Chrome

### ISSUE THREAD

**Issue by kkinder** [bytepixie/snippetpixie#25]
**Describe the bug**
Per the description, SnippetPixie, while working fine in most apps, does not seem to expand text fields in Google Chrome. Just testing it right now, submitting this issue, nothing happens after typing the expansion text.

Steps to reproduce are self-explanatory.

**Desktop (please complete the following information):**
 - OS: elementary OS 5.0 Juno
 - Snippet Pixie Version 1.0.0
 - Related Application Chrome

**Comment by ianmjones** [comment]
Thanks for the bug report @kkinder.

At the moment it looks like Firefox is best supported (just so happens I use Firefox 😉), using Chromium I can't even get it to register that its window is now active (so I suspect the same happens for Chrome).

**Comment by ianmjones** [comment]
Chrome, Chromium, and its cousins, including any Electron apps, to all intents and purposes have zero accessibility features on Linux at the moment, and unfortunately Snippet Pixie uses the Accessibility Tool Kit (ATK) to do its thing.

This is a known problem with Chrome etc and being worked, hopefully Snippet Pixie will start to work with it soon(ish).

Master Orca (screen reader that uses ATK) Chromium bug:
Issue 24585: Orca screen reader doesn't work with chromium
https://bugs.chromium.org/p/chromium/issues/detail?id=24585

There seems to be some recent progress:
Issue 866338: [Orca] Text input fields in HTML and in browser chrome are inaccessible
https://bugs.chromium.org/p/chromium/issues/detail?id=866338

**Comment by Hedronmx** [comment]
I am using firefox and I don't get the expanding text...

**Comment by ianmjones** [comment]
@Hedronmx Is that on elementary OS or another Linux distribution, and which version?

Is the problem on all sites, or a few in particular, and can you give a couple of examples that you would like it to work on most?

**Comment by Hedronmx** [comment]
eOS Juno, all sites.

I have a bar that has a facebook page and I always post the same message at the end of every post. I want to have a quick way to always post this.

As well as other code snippets, for example running as a snippet
npm version patch
yarn release

**Comment by Hedronmx** [comment]
Any way to fix this?

**Comment by ianmjones** [comment]
> Any way to fix this?

As mentioned above, not yet.

When I get some time I am going to look at whether things can be done without using the accessibility framework.

**Comment by BitBrother** [comment]
As an alternative, maby, use xdotool for fix the problem.

**Comment by ianmjones** [comment]
> As an alternative, maby, use xdotool for fix the problem.

Did look at that and the whole `xtst` area when setting out, it looks great for the expansion side of things, but unfortunately doesn't help with detecting abbreviations to trigger the expansion.

It's also very tied to X11, whereas AT-SPI isn't, and should (does in my testing) work under Wayland too as it's an independent dbus service/API.
