### ISSUE TITLE
Improve translations

### ISSUE THREAD

**Issue by NathanBnm** [bytepixie/snippetpixie#28]
I mean that these strings are corresponding to icons and should not be translated. Am I right ?

`#: src/WelcomeView.vala:24`
`msgid "document-import"`
`msgstr ""`

and

`#: src/WelcomeView.vala:24`
`msgid "document-import"`
`msgstr ""`

and

`#: src/WelcomeView.vala:25`
`msgid "help-contents"`
`msgstr ""`

**Comment by ianmjones** [comment]
Thanks for the bug report @NathanBnm!

Yes, you're right, looks like I accidentality wrapped the icon name strings with `_( ... )`. I guess it's possible that different icons might be used for different locales, but that would likely be implemented at the OS level with a different icon for the same identifier.

I'll fix that up in a bug release and will update the `.po` files. If you're currently working on the `fr.po` file feel free to either just use the same icon string value or delete the entry as I expect it'll go away anyway.

It was your previous PR that got me interested in fixing up the translations, first step was getting to grips with how it works and making sure `.po` files were generated for a manageable list of languages. I still have a bunch of things to fix though.

Thanks for your help, very much appreciated!

**Comment by NathanBnm** [comment]
> Thanks for the bug report @NathanBnm!
> 
> Yes, you're right, looks like I accidentality wrapped the icon name strings with `_( ... )`. I guess it's possible that different icons might be used for different locales, but that would likely be implemented at the OS level with a different icon for the same identifier.

You're welcome 👍 Actually it's not possible to change icons depending on locales, so these strings should not be translated.

**Comment by ianmjones** [comment]
Accidentally closed, re-opening.
