### ISSUE TITLE
Translations aren't working

### ISSUE THREAD

**Issue by NathanBnm** [bytepixie/snippetpixie#34]
See #33

**Comment by ianmjones** [comment]
Did you...

```
sudo ninja install
cd
com.github.bytepixie.snippetpixie --stop
com.github.bytepixie.snippetpixie
```

Basically, it needs to be installed to update the translations.
You'll likely need to stop the currently running version (it has a backgroud process).
And then you open Snippet Pixie again either from the Applications, or as above, from the command line.

**Comment by NathanBnm** [comment]
@ianmjones I'm going to check

**Comment by NathanBnm** [comment]
@ianmjones this is working now, I just made some adjustments. You can merge #33.
Closing this.
