### ISSUE TITLE
Expansion not working in Terminal (io.elementary.terminal)

### ISSUE THREAD

**Issue by jtrees** [bytepixie/snippetpixie#43]
**Describe the bug**
Snippets don't expand when typing them in the terminal.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a snippet with the abbreviation "foo" and the body "bar".
2. Open terminal.
3. Type "foo".

**Expected behaviour**
The text "foo" should be replaced with "bar".

**Screenshots**
![Screenshot from 2019-07-26 09-44-05](https://user-images.githubusercontent.com/5802758/61935129-23a6ea80-af8a-11e9-8e85-fef43502c790.png)

**Desktop**
 - OS: elementary OS 5.0 Juno
 - Snippet Pixie Version 1.2.1
 - Related Application: Terminal (`io.elementary.terminal`)

**Additional context**
I use `zsh`, but got the same behaviour in `bash`.

**Comment by ianmjones** [comment]
Thanks for the bug report @jtrees.
