### ISSUE TITLE
Very slow when running while Libre Office Calc is running

### ISSUE THREAD

**Issue by freaktechnik** [bytepixie/snippetpixie#44]
**Describe the bug**
I installed snippet pixie to try it out and forgot about it - never really used it in my workflow. Then LibreOffice Calc started to lag, and I checked out what was so slow with htop, and it was snippet pixie using about 78% CPU resources.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start snippet pixie
2. Start LibreOffice Calc
3. Try to type in the spreadsheet

**Expected behaviour**
LibreOffice Calc is normally usable.

**Comment by jtrees** [comment]
Came here to report the same thing.
