### ISSUE TITLE
Issue with entering normal text when SP is enabled (since 1.3.1)

### ISSUE THREAD

**Issue by phase1geo** [bytepixie/snippetpixie#61]
**Describe the bug**
Ever since upgrading to version 1.3.1, if Snippet Pixie is enabled, I am unable to enter normal text in most applications. Entered characters are being deleted and making entering normal text impossible.

**Desktop (please complete the following information):**
 - elementary OS 5.1.3 (latest version as of 4/21/2020)
 - SP version 1.3.1

**Comment by ianmjones** [comment]
Thanks @phase1geo

I have seen this, but super rarely, and it has been very hard to replicate.

Please could you list 2 or 3 apps that you see this happening in the most?

**Comment by phase1geo** [comment]
- Albert
- Epiphany text form fields
- Tcl text widgets
