### ISSUE TITLE
Typing hangs while “Auto expand snippets” is enabled

### ISSUE THREAD

**Issue by cassidyjames** [bytepixie/snippetpixie#76]
**Describe the bug**

When typing in GTK apps with Snippet Pixie set to expand snippets, it seems like my typing input hangs up pretty frequently. It _might_ happen more frequently f I set up a shortcut using a word I might type without the `` ` ``, like ``test` ``, but I haven't been able to nail that down yet.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install Snippet Pixie and ensure "Auto expand snippets" is enabled
2. Open a GTK app with text input, like Code or Typewriter (from AppCenter)
3. Start typing at a regular/quick pace
4. See typing hang pretty frequently
5. Disable "Auto expand snippets"
6. Type in the GTK app and see it not hang

**Expected behaviour**

Typing is not affected by Snippet Pixie until I actually type something to be expanded.

**Desktop (please complete the following information):**
 - OS: elementary OS 5.1.7 Hera
 - Snippet Pixie Version: 1.4.0
 - Related Application: elementary Code, Typewriter (from AppCenter)

**Comment by ianmjones** [comment]
Hey @cassidyjames, thank you very much for the bug report.

I think I also saw this kind of thing in a couple of scenarios, and hopefully fixed them in the just submitted version 1.4.1.

Once that version has made it through review (or you happen to be the lucky fella that gets to review it :wink:), please let me know if 1.4.1 makes a significant difference or not? :crossed_fingers: 

This isn't really information you need, but for anyone with a smidgeon less experience with elementary OS than Cassidy who finds this issue ... the usual log out and back in, or use the right-click on app's icon and select "Stop Snippet Pixie" and then start it again are required for you to be able to see this particular fix.

**Comment by cassidyjames** [comment]
@ianmjones 1.4.1 was accepted into AppCenter and I haven't seen the issue since. :)

**Comment by ianmjones** [comment]
Excellent, thanks for testing that and confirming the fix @cassidyjames, much appreciated. :tada:
